# Generated by Django 5.2.1 on 2025-08-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ship_type', models.CharField(max_length=50, unique=True, verbose_name='船型')),
                ('ship_subtype', models.CharField(blank=True, max_length=100, null=True, verbose_name='船型细分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '船型',
                'verbose_name_plural': '船型',
                'ordering': ['ship_type'],
            },
        ),
    ]
