# Generated by Django 5.2.1 on 2025-08-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0002_person_role_permission_personrole_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypicalSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=100, verbose_name='分段名称')),
                ('section_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='分段编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分段描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.shiptype', verbose_name='船型')),
            ],
            options={
                'verbose_name': '典型分段',
                'verbose_name_plural': '典型分段',
                'ordering': ['ship_type', 'section_name'],
                'unique_together': {('ship_type', 'section_name')},
            },
        ),
    ]
