# Generated by Django 5.2.1 on 2025-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0003_typicalsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=100, unique=True, verbose_name='工序名称')),
                ('process_code', models.CharField(max_length=20, unique=True, verbose_name='工序编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='工序描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '作业工序',
                'verbose_name_plural': '作业工序',
                'ordering': ['process_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type_name', models.CharField(max_length=100, unique=True, verbose_name='作业工种名称')),
                ('work_type_code', models.CharField(max_length=20, unique=True, verbose_name='作业工种编码')),
                ('standard_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='标准作业工时')),
                ('description', models.TextField(blank=True, null=True, verbose_name='工种描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('related_processes', models.ManyToManyField(blank=True, to='drawings.workprocess', verbose_name='关联工序')),
            ],
            options={
                'verbose_name': '作业工种',
                'verbose_name_plural': '作业工种',
                'ordering': ['work_type_name'],
            },
        ),
    ]
