# Generated by Django 5.2.1 on 2025-08-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0004_workprocess_worktype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workprocess',
            options={'ordering': ['work_type', 'process_name'], 'verbose_name': '作业工序', 'verbose_name_plural': '作业工序'},
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='related_processes',
        ),
        migrations.AddField(
            model_name='workprocess',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='工时系数'),
        ),
        migrations.AddField(
            model_name='workprocess',
            name='work_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='作业工时'),
        ),
        migrations.AddField(
            model_name='workprocess',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drawings.worktype', verbose_name='关联工种'),
        ),
    ]
