# Generated by Django 5.2.1 on 2025-08-30 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0005_alter_workprocess_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, unique=True, verbose_name='项目名称')),
                ('classification_society', models.CharField(max_length=100, verbose_name='所属船级社')),
                ('delivery_date', models.DateField(verbose_name='交船日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.shiptype', verbose_name='所属船型')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'ordering': ['-created_at'],
            },
        ),
    ]
