# Generated by Django 5.2.1 on 2025-08-30 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0006_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=50, unique=True, verbose_name='分段号')),
                ('planned_start_date', models.DateField(verbose_name='计划开始时间')),
                ('on_block_date', models.DateField(verbose_name='上胎日期')),
                ('off_block_date', models.DateField(verbose_name='下胎日期')),
                ('end_date', models.DateField(verbose_name='结束时间')),
                ('block_number', models.CharField(max_length=20, verbose_name='胎架号')),
                ('model_received', models.BooleanField(default=False, verbose_name='模型接收')),
                ('bom_received', models.BooleanField(default=False, verbose_name='BOM接收')),
                ('start_conditions_met', models.BooleanField(default=False, verbose_name='满足开工条件')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.project', verbose_name='所属项目')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.typicalsection', verbose_name='分段类型')),
            ],
            options={
                'verbose_name': '分段管理',
                'verbose_name_plural': '分段管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
