# Generated by Django 5.2.1 on 2025-08-31 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0007_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_code', models.CharField(max_length=50, unique=True, verbose_name='托盘编码')),
                ('pallet_name', models.CharField(max_length=100, verbose_name='托盘名称')),
                ('pallet_details', models.TextField(help_text='例如：零部件c1、c2、b1、b2等，或舾装件条目', verbose_name='托盘明细')),
                ('required_date', models.DateField(verbose_name='需求日期')),
                ('is_received', models.BooleanField(default=False, verbose_name='是否接收')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.project', verbose_name='所属项目')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.section', verbose_name='所属分段')),
            ],
            options={
                'verbose_name': '托盘管理',
                'verbose_name_plural': '托盘管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
