# Generated by Django 5.2.1 on 2025-08-31 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0008_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='required_date',
            field=models.DateField(blank=True, null=True, verbose_name='需求日期'),
        ),
    ]
