# Generated by Django 5.2.1 on 2025-09-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawings', '0009_alter_pallet_required_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='工艺流程名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='工艺流程描述')),
                ('estimated_total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='预估总工时')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.shiptype', verbose_name='船型')),
                ('typical_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.typicalsection', verbose_name='典型分段')),
            ],
            options={
                'verbose_name': '标准工艺流程',
                'verbose_name_plural': '标准工艺流程',
                'ordering': ['ship_type', 'typical_section', 'name'],
                'unique_together': {('ship_type', 'typical_section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProcessFlowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('step_order', models.PositiveIntegerField(verbose_name='步骤顺序')),
                ('parallel_group', models.PositiveIntegerField(default=0, help_text='相同组号的步骤可以并行执行，0表示顺序执行', verbose_name='并行组号')),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='预估工时')),
                ('description', models.TextField(blank=True, null=True, verbose_name='步骤描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='必须在此步骤之前完成的步骤', to='drawings.processflowstep', verbose_name='前置步骤')),
                ('work_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.workprocess', verbose_name='作业工序')),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawings.standardprocessflow', verbose_name='所属工艺流程')),
            ],
            options={
                'verbose_name': '工艺流程步骤',
                'verbose_name_plural': '工艺流程步骤',
                'ordering': ['process_flow', 'step_order', 'parallel_group'],
                'unique_together': {('process_flow', 'step_order')},
            },
        ),
    ]
